steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      export commit_message=$(git log -1 --pretty=format:"%s")
      echo "Latest commit message: $commit_message"
      env | grep "^build_" > /workspace/build_vars
    
  # Step 1: Authenticate with Octopus Deploy
  - name: 'google/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'auth'
      - 'configure-docker'
  # Step 2: Create a new version in Octopus Deploy
  - name: 'docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'docker run --rm -e OCTOPUS_CLI_SERVER=https://wrushu.octopus.app -e OCTOPUS_CLI_API_KEY=API-FURAOUECZ3M6VELG044KJRRZB9VFYPB octopusdeploy/octo create-release --project=projects-2 --version=2021.1.35 --releaseNotes="$commit_message"'
