
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    commit_message=$(git log -1 --pretty=format:"%s")
    echo "Latest commit message: $commit_message"
    
# substitutions:
#   _MY_COMMIT_MESSAGE: COMMIT_MESSAGE, test
