steps:
- id: "Store Values"
  name: 'gcr.io/cloud-builders/git'
  entrypoint: bash
  args:
    - -c
    - |
      # Save a value to persistent volume mount: "/workspace"
      commit_message=$(git log -1 --pretty=format:"%s")
      echo "$commit_message" > /workspace/first.txt
  
- name: 'google/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'auth'
    - 'configure-docker'
# In the next step, everything in the environment is discarded
# EXCEPT items in "/workspace"
- id: "Read Values"
  name: ubuntu
  entrypoint: bash
  args:
    - '-c'
    - 'docker run --rm -e OCTOPUS_CLI_SERVER=https://wrushu.octopus.app -e OCTOPUS_CLI_API_KEY=API-FURAOUECZ3M6VELG044KJRRZB9VFYPB octopusdeploy/octo create-release --project=projects-2 --version=2021.1.38 --releaseNotes=$(cat /workspace/first.txt)' 

