steps:
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        OUTPUT=$(echo "Hello, world!")
        echo "Output is: $OUTPUT"
substitutions:
  _MY_VARIABLE: $(OUTPUT)
