steps:
  # Step 1: Generate a value and save it to a file
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MY_VALUE=$(echo "Hello, World!")
        echo "MY_VALUE=$MY_VALUE" > my-vars.env
    id: generate-value
    env:
      - MY_VALUE=$MY_VALUE

  # Step 2: Use the generated value from Step 1
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "The value of MY_VALUE is: ${MY_VALUE}"
    id: use-value
    env:
      - MY_VALUE=$MY_VALUE

options:
  substitutionOption: ALLOW_LOOSE
