
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git log -1 --pretty=format:"%s" > temp
    echo "Latest commit message: $temp"
    
# substitutions:
#   _MY_COMMIT_MESSAGE: COMMIT_MESSAGE
