steps:
  # Step 1: Generate a value and set it as an environment variable
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MY_VALUE=$(echo "Hello, World!")
        echo "MY_VALUE=$MY_VALUE" >> ${_OUTPUTS_DIR}/my-env-vars.env
    env:
      - 'MY_VALUE=unset'

  # Step 2: Use the generated value from Step 1
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source ${_INPUTS_DIR}/my-env-vars.env
        echo "The value of MY_VALUE is: $MY_VALUE"
    volumes:
      - name: 'my-env-vars'
        path: '/workspace'
    env:
      - 'MY_VALUE=unset'
    waitFor:
      - '-'

options:
  volumes:
    - name: 'my-env-vars'
      path: '/workspace'
